services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:7.2-alpine-latest
    container_name: zabbix-server
    depends_on:
      - mysql
    environment:
      TZ: Europe/Moscow
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "${ZABBIX_MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${ZABBIX_MYSQL_PASSWORD_ROOT}"
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    restart: always
  
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:7.2-alpine-latest
    container_name: zabbix-web
    depends_on:
      - mysql
      - zabbix-server
    environment:
      TZ: Europe/Moscow
      DB_SERVER_HOST: "mysql"
      ZBX_SERVER_HOST: "zabbix-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "${ZABBIX_MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${ZABBIX_MYSQL_PASSWORD_ROOT}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:8080"
    networks:
      - default
    restart: always 

  mysql:
    image: mysql:8.0
    container_name: zabbix-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "${ZABBIX_MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${ZABBIX_MYSQL_PASSWORD_ROOT}"
    networks:
      - default
    volumes:
      - ./zabbix/database/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
